import { Navbar } from './components/navbar/Navbar.js'
import Footer from './components/footer/footer.js'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <div className='content'>
          <Navbar />

          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
