import Footer from './footer.js'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Navbar } from './Navbar.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <div className={inter.className}>
        <div className='content'>
          <Navbar />
          <div className=''>
            {children}
          </div>
          <Footer />
        </div>
      </div>
    </div>
  )
}
