import { Navbar } from './Navbar.js'
import Footer from './footer.js'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, showNavBar = true }) {
  return (
    <html>
      <body className={inter.className}>
        <div className='content'>
          {showNavBar && <Navbar />}
          <div className=''>
            {children}
          </div>
          {showNavBar && <Footer />}
        </div>
      </body>
    </html>
  )
}
